/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        neutral: {
          'primary-soft': 'var(--neutral-primary-soft)',
          'primary': 'var(--neutral-primary)',
          'primary-medium': 'var(--neutral-primary-medium)',
          'primary-strong': 'var(--neutral-primary-strong)',
          'secondary-soft': 'var(--neutral-secondary-soft)',
          'secondary': 'var(--neutral-secondary)',
          'secondary-medium': 'var(--neutral-secondary-medium)',
          'secondary-strong': 'var(--neutral-secondary-strong)',
          'tertiary-soft': 'var(--neutral-tertiary-soft)',
          'tertiary': 'var(--neutral-tertiary)',
          'tertiary-medium': 'var(--neutral-tertiary-medium)',
          'quaternary': 'var(--neutral-quaternary)',
          'quaternary-medium': 'var(--quaternary-medium)',
          gray: 'var(--gray)',
        },
        brand: {
          DEFAULT: 'var(--brand)',
          softer: 'var(--brand-softer)',
          soft: 'var(--brand-soft)',
          medium: 'var(--brand-medium)',
          strong: 'var(--brand-strong)',
        },
        success: {
          DEFAULT: 'var(--success)',
          soft: 'var(--success-soft)',
          medium: 'var(--success-medium)',
          strong: 'var(--success-strong)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          soft: 'var(--danger-soft)',
          medium: 'var(--danger-medium)',
          strong: 'var(--danger-strong)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          soft: 'var(--warning-soft)',
          medium: 'var(--warning-medium)',
          strong: 'var(--warning-strong)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          default: 'var(--border-default)',
          'default-subtle': 'var(--border-default-subtle)',
          'default-medium': 'var(--border-default-medium)',
          'default-strong': 'var(--border-default-strong)',
          muted: 'var(--border-muted)',
          brand: 'var(--border-brand)',
          'brand-subtle': 'var(--border-brand-subtle)',
          'brand-light': 'var(--border-brand-light)',
          success: 'var(--border-success)',
          'success-subtle': 'var(--border-success-subtle)',
          danger: 'var(--border-danger)',
          'danger-subtle': 'var(--border-danger-subtle)',
          warning: 'var(--border-warning)',
          'warning-subtle': 'var(--border-warning-subtle)',
          light: 'var(--border-light)',
          'light-medium': 'var(--border-light-medium)',
          'light-subtle': 'var(--border-light-subtle)',
          buffer: 'var(--border-buffer)',
          'buffer-medium': 'var(--border-buffer-medium)',
          'buffer-strong': 'var(--border-buffer-strong)',
        },
        heading: 'var(--heading)',
        body: 'var(--body)',
        'body-subtle': 'var(--body-subtle)',
        subtle: 'var(--body-subtle)', // Map subtle text for backward compatibility
        'fg-brand': 'var(--fg-brand)',
        'fg-brand-strong': 'var(--fg-brand-strong)',
        'fg-success': 'var(--fg-success)',
        'fg-success-strong': 'var(--fg-success-strong)',
        'fg-danger': 'var(--fg-danger)',
        'fg-danger-strong': 'var(--fg-danger-strong)',
        'fg-warning': 'var(--fg-warning)',
        'fg-warning-subtle': 'var(--fg-warning-subtle)',
        'fg-disabled': 'var(--fg-disabled)',
        dark: 'var(--dark)',
        'dark-strong': 'var(--dark-strong)',
      },
      fontFamily: {
        mono: ['var(--font-mono)', 'monospace'],
        sans: ['var(--font-sans)', 'sans-serif'],
      },
      borderRadius: {
        base: 'var(--radius-base)',
        default: 'var(--radius-default)',
        sm: 'var(--radius-sm)',
      },
      boxShadow: {
        '2xs': 'var(--shadow-2xs)',
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inset': 'var(--shadow-inset)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 300ms cubic-bezier(0.16, 1, 0.3, 1) both',
        pulseGlow: 'pulseGlow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
